version: '2'

#volumes: 
    #pulsevolume:
services:
        
    webaudioserver:
        build: ./docker-images/nodejs
        image: syntithenai/nodejs
        #depends_on: ['mongo']
        restart: always
        volumes:
          - "./snips-react-satellite:/usr/src/app/"
        #environment:
          #VIRTUAL_HOST: meeka.syntithenai.com
          #VIRTUAL_PORT: 7000
          #LETSENCRYPT_HOST: meeka.syntithenai.com
          #LETSENCRYPT_EMAIL: stever@syntithenai.com
          
        ports:
          - "3000:3000"
        
   
    ## ===========================================================================================   
    ## SNIPS ALL IN ONE
    ## ===========================================================================================   
    snips:
        depends_on: ['mosquitto']
        restart: always
        image: syntithenai/snips
        build: ./docker-images/snips
        # use paprefs to enable network server
        environment: ['PULSE_SERVER=192.168.1.100','PULSE_COOKIE=/tmp/pulse-cookie']
        volumes:
            - ./assistants/meekahome/assistant:/usr/share/snips/assistant
            - /home/stever/.config/pulse/cookie:/tmp/pulse-cookie
 
                
    # ==========================================================================================
    # MQTT MESSAGING QUEUE -  WITH WEBSOCKETS
    # ===========================================================================================
    mosquitto:
        # see docker-images/manifest*.yml for multi arch config
        image: syntithenai/mosquitto
        restart: always
        ports:
            - 1883:1883
            # websockets enabled (for browser clients)
            - 9001:9001 
        volumes:
          # enable websockets
          - ./mosquitto-websockets.conf:/etc/mosquitto/conf.d/websockets.conf
          
     
